name: rise-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - bokeh
  - rise
  - nbpresent
  - spacy
  - pip:
    - jupyter-contrib-nbextensions
    - dframcy
    - scattertext
    - ipython
    - faiss-cpu
    - whatlies
